In [2]:
import numpy as np
import pandas as pd
from datetime import datetime


### Exercício 1
- Crie um array Numpy com 10 elementos inteiros aleatórios entre 0 - 100 e exiba os valores e tipos de dado do array

In [3]:
arr1 = np.random.randint(0, 100, size=10)
print(arr1)

[44 54 29 10  7 35 14 14 46 54]


### Exercício 2
- Crie uma matriz de 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz

In [10]:
arr2 = np.random.rand(5,5)
print(f"min: {arr2.min()}")
print(f"max: {arr2.max()}")
print(f"max: {arr2.mean()}")

min: 0.003967677677713222
max: 0.9941314472093579
max: 0.4515209490982243


### Exercício 3
- Crie um array com 10 elementos aleartórios no intervalo [0,1). Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro

In [24]:
arr3 = np.random.rand(10)
print(arr3)
arr3_mult = (arr3*10).astype(int)
print(arr3_mult)


[0.73717039 0.4288149  0.81219517 0.05376164 0.84757684 0.95100922
 0.32676162 0.19775989 0.47302698 0.17562431]
[7 4 8 0 8 9 3 1 4 1]


### Exercício 4
- Crie um array de duas dimensoes com shape (3,3) e valores aleatórios no intervalo [0,9]. Subsatitua todos os elementos da segunda linha por -1

In [34]:
arr4 = np.random.randint(0,9,(2,2))
arr4[-1] = -1
print(arr4)

[[ 5  4]
 [-1 -1]]


### Exercício 5
Crie um DataFrame com as seguintes informações:
- Coluna "fruta": "banana", "maça", "pera"
- Coluna "preco": 7.9, 10.20, 11.80 
- Coluna "quantidade": 12, 3, 4

In [38]:
tabela = {"fruta": ["Banana", "Maça", "Pera"], "preco":[7.90,10.20,11.80], "quantidade":[12,3,4]}
df = pd.DataFrame(tabela)
print(df)

    fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4
